[package]
name = "geocentric"
description = "Conversion between geodetic and geocentric (cartesian) coordinates"
version = "0.1.3"
edition = "2024"
license = "MIT"
repository = "https://github.com/ciscorn/geocentric-rs"
categories = ["science::geo"]

[dependencies]
